apiVersion: v1
kind: Service
metadata:
  name: fsl-service
  namespace: production
spec:
  selector:
    app: fsl-challenge
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  clusterIP: None
